Mellanox/k8s-rdma-shared-dev-plugin

example/test-hca-pod.yaml, images/k8s-rdma-shared-dev-plugin-ds-pre-1.16.yaml, images/k8s-rdma-shared-dev-plugin-ds.yaml
Changed the example pod image from the mofed image to the mellanox
rping image. also changed the daemonsets images to take from the
mellanox repo, instead of the rdma repo.
=> Changes the example pod image to mellanox/rping-test

Makefile
This commit allow to run unit tests using "test" make rule without
running the "lint" rule.
=> Seprate lint rule from test rule in Makefile

go.mod, pkg/resources/resources_manager.go, pkg/resources/server.go, pkg/resources/server_test.go, pkg/resources/watcher.go, pkg/resources/watcher_test.go, pkg/types/mocks/ResourceServer.go, pkg/types/types.go
When kubelet restart the server triggers restart which will be aborted
in the process because the function Watch that triggered the restart
will be stopped
This patch fix the issue of restartiing failure
=> Fix - device plugin server failed to restart correctly in legacy mode

pkg/resources/pci_net_device.go, pkg/resources/rdma_device_spec.go, pkg/resources/resources_manager.go, pkg/resources/resources_manager_test.go, pkg/types/mocks/RdmaDeviceSpec.go, pkg/types/types.go
When run device plugin while booting and modules are not fully
loaded device plugin is missing RDMA devices which causes unwanted
behaviour for the device plugin consumers.
This change causes the device plugin to fail in case there are
missing RDMA devices
=> Fail device plugin in case there are missing RDMA  devices

README.md, cmd/k8s-rdma-shared-dp/main.go, images/k8s-rdma-shared-dev-plugin-config-map.yaml, pkg/resources/resources_manager.go, pkg/resources/resources_manager_test.go, pkg/types/types.go
This change brings a new config field which is used to config the periodic update interval of the device plugin.
When periodic update interval is 0 periodic update is disabled
Fixes #27
=> Add config field for periodic update interval

images/k8s-rdma-shared-dev-plugin-ds.yaml
Currently rdma resources "/dev/infiniband" are mounted by using
hostNetwork, where rdma resources will not be tracked when kernel
modules/drivers are installed after deploying rdma shared device
plugin.
This patch mounts "/dev/" inside the container with
volumes which keeps tracking the changes to devices changes,
mounting "/dev/" not "/dev/infiniband" because mounted dev dir
will be broken when dir is deleted, "/dev/infiniband" is deleted
when rdma modules unloaded
=> Mount /dev/inside rdma shared device plugin

cmd/k8s-rdma-shared-dp/main.go, pkg/resources/resources_manager.go, pkg/types/types.go
We support only shared mode for RDMA subsystem [1]. This patch
checks the current mode and tries to change it to the 'shared'.
[1] https://man7.org/linux/man-pages/man8/rdma-system.8.html
Closes: #6
Signed-off-by: Ivan Kolodyazhny <ikolodiazhny@nvidia.com>
=> Validate RDMA subsystem network namespace mode on startup

pkg/resources/server.go
RDMA resources output doesn't contain a lot of useful information
but floods a logs with thousands of similar records. This patch
changes logs output to print only resources count.
Signed-off-by: Ivan Kolodyazhny <ikolodiazhny@nvidia.com>
=> Do not print all RDMA resources to logs

Dockerfile
This patch will fix CVEs in following packages:
* libssl1.1 - CVE-2021-3711 - http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3711
* libssl1.1 - CVE-2021-3712 - http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3712
* libcrypto1.1 - CVE-2021-3712 - http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3712
* apk-tools - CVE-2021-36159 - http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-36159
* libcrypto1.1 - CVE-2021-3711 - http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3711
Signed-off-by: Ivan Kolodyazhny <ikolodiazhny@nvidia.com>
=> Update base Alpine image to 3.14.3

README.md
Currently latest alpine image points to v3.14.0.
Building image with docker older than 20.10.0 will
cause image build to fail with:
`make: /bin/sh: Operation not permitted`
More info can be found in alpine release notes:
https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2
Add a note to build image with Docker 20.10.0 or newer.
Signed-off-by: Adrian Chiris <adrianc@nvidia.com>
=> Add note to build image with newer Docker

pkg/resources/server.go, pkg/resources/server_test.go
This PR solves two problems:
- Fix deadlock caused by nesting
During kubelet restart, continuous updating multiple times will
cause the channel to block and the lock will not be released,
which will lead to a deadlock in ListAndWatch.
- Stop ListAndWatch when stream is closed
Kubelet restart will cause the connection to be disconnected and the
stream to be closed. We need to actively stop the ListAndWatch handler
to avoid goroutine leaks, which may casue bugs like #48 .
=> Fix dead lock and goroutine leaks in rare cases

images/k8s-rdma-shared-dev-plugin-ds.yaml
scheduler.alpha.kubernetes.io is deprecated in k8s v1.16+.
This emits a warning when deploying components which have
this annotation:
Warning: spec.template.metadata.annotations
[scheduler.alpha.kubernetes.io/critical-pod]: non-functional in v1.16+;
use the "priorityClassName" field instead
Signed-off-by: Fred Rolland <frolland@nvidia.com>
=> Set priorityClassName instead of annotation

README.md, go.sum, pkg/resources/resources_manager.go, pkg/resources/resources_manager_test.go, pkg/resources/server.go, pkg/resources/server_test.go, pkg/types/types.go
Resource configuration now might optionally
contain a resource prefix.
The previous behavior was to always add "rdma"
prefix to all resources. Now it's a default
option and might be changed if "resourcePrefix"
is provided in the config
Signed-off-by: amaslennikov <amaslennikov@nvidia.com>
=> Extend resource pool configuration with resource prefix option

pkg/resources/resources_manager.go
Strict validation such as for resource name (only numbers and symbols) should not apply for the resource prefix as it might contain different characters (e.g. "." in the domain name)
=> Drop validation for resource prefix

Dockerfile
This patch fixes following CVEs:
* https://nvd.nist.gov/vuln/detail/CVE-2022-0778
* https://nvd.nist.gov/vuln/detail/CVE-2018-25032
* https://nvd.nist.gov/vuln/detail/CVE-2022-0778
Signed-off-by: Ivan Kolodiazhny <ikolodiazhny@nvidia.com>
=> Update base image to alpine:3.15.4

go.mod, go.sum
The Kubernetes API Server component in versions 1.1-1.14, and versions prior to 1.15.10, 1.16.7 and 1.17.3 allows an authorized user who sends malicious YAML payloads to cause the kube-apiserver to consume excessive CPU cycles while parsing YAML.
Signed-off-by: Ivan Kolodiazhny <ikolodiazhny@nvidia.com>
=> Bump yaml package to v2.2.8 and golang to v1.18

.github/workflows/image-push-master.yaml, .github/workflows/release.yaml, images/k8s-rdma-shared-dev-plugin-ds.yaml
Docker cannot work with uppercased letters in the images names, so we need to lowercase the repo name before proceeding with images pushes
Also, adapt the daemonset config to take the image from ghcr
=> Adapt github actions to the uppercase repo name

.github/workflows/build.yml, Makefile
- use go install to install relevant binaries
- dont use .gopath as alternate GOPATH, rely on
go modules doing its job
- remove BASE var as its not longer needed
Signed-off-by: adrianc <adrianc@nvidia.com>
=> Makefile refactors

images/k8s-rdma-shared-dev-plugin-ds-pre-1.16.yaml, images/k8s-rdma-shared-dev-plugin-ds.yaml
There is no need to mount the whole '/var/lib/kubelet/' directory into a pod. It's enough to mount only '/var/lib/kubelet/device-plugins' and '/var/lib/kubelet/plugins_registry' directories.
=> Update device plugins volumes mounts

pkg/resources/rdma_device_spec.go
"issm" devices should be created only if link type is InfiniBand. It's not required for Ethernet devices.
=> Remove "issm" device from required list

Dockerfile
Newer hwdata-pci and kmod available in base image
[2/2] STEP 2/5: RUN apk add --no-cache kmod=30-r3 hwdata-pci=0.370-r0 fetch https://dl-cdn.alpinelinux.org/alpine/v3.21/main/x86_64/APKINDEX.tar.gz fetch https://dl-cdn.alpinelinux.org/alpine/v3.21/community/x86_64/APKINDEX.tar.gz ERROR: unable to select packages:
hwdata-pci-0.390-r0:
breaks: world[hwdata-pci=0.370-r0]
kmod-33-r2:
breaks: world[kmod=30-r3]
Error: building at STEP "RUN apk add --no-cache kmod=30-r3 hwdata-pci=0.370-r0": while running runtime: exit status 2
=> chore: fix docker file

Dockerfile
The alpine:3.21.3 image don't contain hwdata-pci package so failes to run in container.
`Error: error discovering host devices error getting PCI info: No pci-ids DB files found (and network fetch disabled)`
=> Install hwdata-pci package in Dockerfile

.github/workflows/build.yml, .github/workflows/codeql.yaml, .github/workflows/image-push-master.yaml, .github/workflows/release-ubi.yaml, .github/workflows/release.yaml, .github/workflows/static-scan.yaml
ubuntu 20.04 image is deprecated and is scheduled to be retired on april 1st.
align all images to use 24.04
=> chore: align OS in workflow
